Feat/convert query string
pahud/cdk-cloudfront-plus pull request #53
Opened 2021-04-04 13:06 UTC by HsiehShuJeng

draft PR

2021-04-05 04:31 UTC, pahud requested changes

2021-04-05 04:31 UTC, pahud commented on src/demo/convert-query-string/index.ts
> +const convertQueryString = new extensions.ConvertQueryString(stack, 'LambdaEdge');
As we discussed [here](https://github.com/pahud/cdk-cloudfront-plus/issues/23#issuecomment-813032522), maybe we can provide a `args` array property for the construct class so we don't have to create an external config file for the whitelisted args?

If you use `NodejsFunction`, you can simply bundling the `definition` like this

https://github.com/pahud/cdk-cloudfront-plus/blob/ed256843aeefb041b11c64a6377e63688b2d92e0/src/extensions.ts#L303
or
https://github.com/pahud/cdk-cloudfront-plus/blob/ed256843aeefb041b11c64a6377e63688b2d92e0/src/extensions.ts#L335

I believe it would be easier with `NodejsFunction` though.

[Looks](https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-lambda-python/lib/function.ts) like PythonFunction has no similar feature like this atm.

2021-04-05 04:31 UTC, pahud commented on src/extensions.ts
> +      templateDescription: 'Cloudfront extension with AWS CDK - Convert a query string to key-value pairs and add them into header.',
```suggestion
      templateDescription: 'Cloudfront extension with AWS CDK - Convert Query String.',
```

2021-04-05 11:34 UTC, HsiehShuJeng commented on src/demo/convert-query-string/index.ts
> +const convertQueryString = new extensions.ConvertQueryString(stack, 'LambdaEdge');
NP.
For those who dig into the discussion, `process.env` is actually not necessary. Merely `COUNTRY_CODE_TABLE` is also fine, take the above as example, the most important thing is that you should remember to reference the variable, `COUNTRY_CODE_TABLE` in the Lambda you're about to build.

2021-04-05 12:10 UTC, pahud requested changes

2021-04-05 12:10 UTC, pahud commented on .projenrc.js
> +    '@aws-cdk/aws-lambda-python',
Do we still need this?

2021-04-05 12:10 UTC, pahud commented on src/extensions.ts
> +  readonly args: Array<string>;
Let's add some description for this property?

2021-04-05 12:42 UTC, HsiehShuJeng commented on .projenrc.js
> +    '@aws-cdk/aws-lambda-python',
According to f49f1ac, this module is not needed anymore.

2021-04-05 12:43 UTC, HsiehShuJeng commented on src/extensions.ts
> +  readonly args: Array<string>;
NP. Have added the documentation on this property, or interface.

2021-04-05 13:24 UTC, guan840912 commented on src/demo/convert-query-string/README.md
> +    # the configuration in `index.tx` under `src/demo/convert-query-string`.
should be `index.ts` ??

2021-04-05 13:43 UTC, pahud requested changes

2021-04-05 13:43 UTC, pahud commented on lambda-assets/extensions/cf-convert-query-string/index.ts
> +     * */
```suggestion
    /**
     * Whitelisted request arguments that will be converted into additional headers
     * `NEEDED_KEYS` is the placeholder for `args` that will be bundled and injected by esbuild.
     * */
```

Actually they are not `environment variables`, let's change the description as suggested.

2021-04-05 13:43 UTC, pahud commented on src/demo/convert-query-string/README.md
> +
Is there any way we can check the backend is receiving new headers correctly?

Maybe we should configure the origin of the CF distribution as `http://postman-echo.com/get` so we can check if the backend is receiving new headers converted by L@E. What do you think?

2021-04-05 13:43 UTC, pahud commented on src/demo/convert-query-string/index.ts
> +    origin: new S3Origin(bucket),
I still don't understand why we need a S3 backed origin for this scenario? Let's discuss this offline.

2021-04-05 13:43 UTC, pahud commented on src/extensions.ts
> +   * @default - No description.
```suggestion
```

Let's remove the @default as we only use `@default` for optional property.

2021-04-05 13:43 UTC, pahud commented on src/extensions.ts
> +   *
```suggestion
  /**
   * The request arguments that will be converted to additional request headers.
   * For example ['key1', 'key2'] will be converted to the header `x-key1` and `x-key2`.
   * Any other request arguments will not be converted.
   *
```

2021-04-05 13:53 UTC, HsiehShuJeng commented on src/demo/convert-query-string/README.md
> +    # the configuration in `index.tx` under `src/demo/convert-query-string`.
yes, you're right

2021-04-05 14:34 UTC, HsiehShuJeng commented on src/demo/convert-query-string/README.md
> +
no specific reason on selecting S3 as origin. For checking whether new headers are received, I'll take your suggestion.

2021-04-05 14:34 UTC, HsiehShuJeng commented on src/demo/convert-query-string/index.ts
> +    origin: new S3Origin(bucket),
as mentioned above

2021-04-06 15:48 UTC, guan840912 approved these changes
LGTM 
any comment @pahud  ??

2021-04-06 15:49 UTC, merged