feat(extensions): global data ingestion
pahud/cdk-cloudfront-plus pull request #62
Opened 2021-04-05 20:22 UTC by titanjer

Fixes #14

2021-04-05 23:11 UTC, pahud requested changes
Nice! Let's address some minor issues in the comments.

2021-04-05 23:11 UTC, pahud commented on src/__tests__/integ.global-data-ingestion.test.ts
> +    firehoseStreamName: firehoseStream.deliveryStreamName ?? 'gg',
```suggestion
    firehoseStreamName: firehoseStream.deliveryStreamName!
```
I believe the `deliveryStreamName` should exist as you already defined it in line 14 and 33.

2021-04-05 23:11 UTC, pahud commented on src/__tests__/integ.global-data-ingestion.test.ts
> +    value: firehoseStream.deliveryStreamName ?? 'gg',
```suggestion
    value: firehoseStream.deliveryStreamName!,
```

2021-04-05 23:11 UTC, pahud commented on src/demo/global-data-ingestion/demo.sh
> +echo "Please open S3 bucket '${BUCKET}' to see the results"
NICE!

2021-04-05 23:11 UTC, pahud commented on src/demo/global-data-ingestion/index.ts
> +  value: firehoseStream.deliveryStreamName ?? 'gg',
```suggestion
  value: firehoseStream.deliveryStreamName!,
```

2021-04-05 23:11 UTC, pahud commented on src/extensions.ts
> +   */
Add a `@deafult` tag here as it's optional property.

2021-04-05 23:11 UTC, pahud commented
HI @guan840912  please help review if you have time. thanks.

2021-04-06 01:50 UTC, guan840912 approved these changes

2021-04-06 02:10 UTC, titanjer commented on src/__tests__/integ.global-data-ingestion.test.ts
> +  // func.role?.addManagedPolicy(iam.ManagedPolicy.fromAwsManagedPolicyName('AmazonKinesisFirehoseFullAccess'));
ok, btw this notes this can not works, I dont know why.

2021-04-06 02:46 UTC, guan840912 approved these changes

2021-04-06 02:48 UTC, merged